INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'water',
    '0',
    'hydrates organism,enhances metabolism,provides minerals',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'apple',
    '47-52',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'banana',
    '89',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'orangelike',
    '53',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'chocolate',
    '531-578',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'egg',
    '155',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'soft_drink',
    '29-43',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'chips',
    '440-540',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'bread',
    '265-313',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'butter',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'milk',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'lemon',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'cheese',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'meat',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'tomato',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'cucumber',
    '',
    '',
    '',
    ''
);

INSERT INTO PRODUCT_DATA(PRODUCT_NAME, ENERGY_VALUE_RANGE, PROS, CONS, ADDITIONAL_INFO) VALUES(
    'ketchup',
    '',
    '',
    '',
    ''
);
