CREATE TABLE PRODUCT_DATA (
    PRODUCT_NAME VARCHAR(12) NOT NULL CONSTRAINT PK_PRODUCT_DATA PRIMARY KEY,
    ENERGY_VALUE_RANGE VARCHAR(8) NOT NULL, 
    PROS VARCHAR(128) NOT NULL,
    CONS VARCHAR(128) NULL,
    ADDITIONAL_INFO VARCHAR(64)
);

CREATE TABLE NAMETAGS (
    PRODUCT_TAG VARCHAR(20) NOT NULL CONSTRAINT PK_NAMETAGS PRIMARY KEY,
    PRODUCT_NAME VARCHAR(12) NOT NULL CONSTRAINT FK_PRODUCT_DATA FOREIGN KEY REFERENCES PRODUCT_DATA(PRODUCT_NAME)
);
